version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  gateway-service:
    build: ./gateway-service
    restart: always
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - .env
    depends_on:
      - user-service
      - admin-service
      - payment-notification-service
      - file-service
    networks:
      - app-network

  user-service:
    build: ./user-service
    restart: always
    command: node src/index.js
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  admin-service:
    build: ./admin-service
    restart: always
    command: node src/index.js
    ports:
      - "${ADMIN_SERVICE_PORT}:${ADMIN_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  payment-notification-service:
    build: ./payment-notification-service
    restart: always
    command: node src/index.js
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  file-service:
    build: ./file-service
    restart: always
    command: node src/index.js
    ports:
      - "${FILE_SERVICE_PORT}:${FILE_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge