import type { Metadata } from "next"
import "./globals.css"
import { Audiowided, OpenSans } from "./fonts"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import { Toaster } from "react-hot-toast"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${Audiowided.variable} ${OpenSans.variable} antialiased`}
//       >
//         <Navbar/>
//         {children}
//         <Toaster position="bottom-right" />
//         <Footer/>
//       </body>
//     </html>
//   )
// }
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Audiowided.variable} ${OpenSans.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navbar />
        <main className="flex-1">{children}</main>
        <Toaster position="bottom-right" />
        <Footer />
      </body>
    </html>
  )
}


