import type { Metadata } from "next"
import "./globals.css"
import { Audiowided, OpenSans } from "./fonts"
import ClientWrapper from "@/components/ClientWrapper"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${Audiowided.variable} ${OpenSans.variable} antialiased min-h-screen flex flex-col`}
      >
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  )
}
