import type { Metadata } from "next";
import "./globals.css";
import { Audiowided, OpenSans } from "./fonts";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Audiowided.variable} ${OpenSans.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}

